# Generated by Django on 2024-11-20

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images/', null=True, blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('availability', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tour_type', models.CharField(choices=[('guided', 'Guided'), ('non-guided', 'Non-Guided')], default='non-guided', max_length=10)),
                ('review_count', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.ForeignKey(on_delete=models.CASCADE, related_name='tours', to='states.state')),
            ],
        ),
    ]
