# Generated by Django 5.1.2 on 2024-11-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('availability', models.BooleanField(default=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/')),
                ('accommodation_type', models.CharField(choices=[('A', 'ACCOMMODATION'), ('S', 'HOME STAYS'), ('H', 'HOTELS')], default='HOTELS', max_length=1)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
