# Generated by Django 5.1.2 on 2024-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='festivals',
            field=models.CharField(default='indepence day', max_length=150),
            preserve_default=False,
        ),
    ]
